function [scenario, egoVehicle,roadCenters,laneSpecification, speed] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.10 (R2021a) and Automated Driving Toolbox 3.3 (R2021a).
% Generated on: 28-Jun-2021 16:06:12

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-4.7 0.2 0;
    2.3 -4.3 0;
    14.6 -13 0;
    26.4 -17.2 0;
    39.5 -19.7 0;
    49.2 -19.2 0;
    53.2 -15.7 0];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Dashed')];
laneSpecification = lanespec(2, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-3.3 -2.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-3.3 -2.9 0;
    2.2 -6.8 0;
    7.4 -10.8 0;
    16.3 -14.8 0;
    24.1 -16.2 0;
    32.6 -17.4 0;
    39.1 -18.5 0;
    45.4 -19.7 0;
    50.4 -19.9 0;
    53.3 -18.9 0];
speed = [10;10;10;10;10;10;10;10;10;10];
speed=10;

trajectory(egoVehicle, waypoints, speed);

